// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDW4hvVUosSE3v7JHE047kxK-tsRRVPs_Y',
    appId: '1:313640457689:web:48e55d868b36044eeeb5c8',
    messagingSenderId: '313640457689',
    projectId: 'campus-sync-32897',
    authDomain: 'campus-sync-32897.firebaseapp.com',
    storageBucket: 'campus-sync-32897.firebasestorage.app',
    measurementId: 'G-X1NG8XS2E9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6kS0U-YzSi1Gd0mmlQsmgQsidqHRdvSs',
    appId: '1:313640457689:android:7dab348ad4433176eeb5c8',
    messagingSenderId: '313640457689',
    projectId: 'campus-sync-32897',
    storageBucket: 'campus-sync-32897.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaWIBicjS-KnYSlxAEWYXsgNs3PCeHwiU',
    appId: '1:313640457689:ios:d53645b225ec5f43eeb5c8',
    messagingSenderId: '313640457689',
    projectId: 'campus-sync-32897',
    storageBucket: 'campus-sync-32897.firebasestorage.app',
    iosClientId: '313640457689-avri4q6lerdtellda7qsn9fb7otbktp6.apps.googleusercontent.com',
    iosBundleId: 'com.example.campusSync',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaWIBicjS-KnYSlxAEWYXsgNs3PCeHwiU',
    appId: '1:313640457689:ios:d53645b225ec5f43eeb5c8',
    messagingSenderId: '313640457689',
    projectId: 'campus-sync-32897',
    storageBucket: 'campus-sync-32897.firebasestorage.app',
    iosClientId: '313640457689-avri4q6lerdtellda7qsn9fb7otbktp6.apps.googleusercontent.com',
    iosBundleId: 'com.example.campusSync',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDW4hvVUosSE3v7JHE047kxK-tsRRVPs_Y',
    appId: '1:313640457689:web:9a8bfdd89d3e0ca7eeb5c8',
    messagingSenderId: '313640457689',
    projectId: 'campus-sync-32897',
    authDomain: 'campus-sync-32897.firebaseapp.com',
    storageBucket: 'campus-sync-32897.firebasestorage.app',
    measurementId: 'G-3J4C96NZEC',
  );

}